### PR TITLE
Patches have been merged upstream since Linux 5.8

### PR DESCRIPTION
**Pull request by ashb**
I'm not sure if the thermald changes have been merged (looking at that next) but the kernel changes are upstreamed already.

### CODE REVIEW

**Comment by mjg59** [comment]
Thanks!

**Comment by ashb** [comment]
To update on my comment, it turns out `thermald` won't run on my laptop (P1 Gen 2) because it is missing the "on lap" detection mode :(

```
/sys/devices/platform/thinkpad_acpi/dytc_lapmode] present: Thermald can't run on this platform
```

That said, with a recent firmware update I haven't noticed the "thermal throttle" messages I used to get spewing in to dmesg anymore, so maybe it's all working better?

**Comment by benzea** [comment]
> To update on my comment, it turns out `thermald` won't run on my laptop (P1 Gen 2) because it is missing the "on lap" detection mode :(
> 
> ```
> /sys/devices/platform/thinkpad_acpi/dytc_lapmode] present: Thermald can't run on this platform
> ```
> 
> That said, with a recent firmware update I haven't noticed the "thermal throttle" messages I used to get spewing in to dmesg anymore, so maybe it's all working better?

Try using Fn+hml to switch the performance mode of the firmware thermal management (and, also update the firmware first). Not entirely sure if the P1G2 has that feature though.

**Comment by ashb** [comment]
Hold fn then press `h`, `m`, `l`? It doesn't seem to do anything, and doesn't change the value in the sysfs file.

Not _hugely_ surprising as the P1G2 is not what I'd call an "ultrabook" by any stretch of the imagination.

**Comment by benzea** [comment]
> Hold fn then press `h`, `m`, `l`? It doesn't seem to do anything, and doesn't change the value in the sysfs file.
> 
> Not _hugely_ surprising as the P1G2 is not what I'd call an "ultrabook" by any stretch of the imagination.

On newer linux versions you'll have a sysfs attribute. Note that you would not necessarily notice an immediate change. But in general, with Fn+H the fan should spin up much earlier for example.

**Pull request merged**
